name = "TaijaBase"
uuid = "10284c91-9f28-4c9a-abbf-ee43576dfff6"
authors = ["Patrick Altmeyer"]
version = "1.0.0"

[compat]
Aqua = "0.8"
Test = "1.6, 1.10"
julia = "1.6, 1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
