name = "TaijaBase"
uuid = "10284c91-9f28-4c9a-abbf-ee43576dfff6"
authors = ["Patrick Altmeyer"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
